### ISSUE TITLE
請問能否把這個輸入法做爲輔助碼融入RIME小鹤双拼中？

### ISSUE THREAD

**Issue by tshiao4695** [mirtlecn/rime-radical-pinyin#1]
如题，即实现类似搜狗输入法的TAB键然后拆字输入和笔画输入进行辅助检索。

**Comment by mirtlecn** [comment]
不太清楚你说得是怎样的辅助检索，你是说类似下图这样反查的意思吗

![2024年01月16日18时40分](https://github.com/mirtlecn/rime-radical-pinyin/assets/76689045/3f64363d-9e6e-461e-9305-c4ab2e61e5d6)

如果是的话，README.md 里面写了大致的写法，Release 界面下也有个用了这个反查方案的输入方案文件做参考

**Comment by tshiao4695** [comment]
实际上如下图，较之你展示的GIF内容，这个搜狗的好处是在于整句的输入中出现了生僻字的话能够快速进行拆分检索。
![动画](https://github.com/mirtlecn/rime-radical-pinyin/assets/50295057/cea44c0d-1811-4c45-8a70-f6f9a9b7f18d)

**Comment by mirtlecn** [comment]
辅助码，简简单单应该弄不好

没研究过。

**Comment by tshiao4695** [comment]
好叭，那我再琢磨琢磨，看看怎么才能把搜狗这个功能移植到RIME上。谢啦！

**Comment by mirtlecn** [comment]
你看看这个项目吧，有现成的 lua 可以用，我试了一下，没有问题

<https://github.com/HowcanoeWang/rime-lua-aux-code>

![1705753664](https://github.com/mirtlecn/rime-radical-pinyin/assets/76689045/f64e3572-b323-4bce-9b8b-0947169e27b5)

@tshiao4695

**Comment by tshiao4695** [comment]
感谢！我前两天参考了你的作品和另外一位老哥的作品，整合了一下弄了个比较接近我之前发的搜狗的效果。
[目前的缺陷就是，按tab比较不容易让肉眼识别光标所在的位置，另外就是零声母的情况和一般小鹤规则不太一样，使用的是双写。详细介绍再CSDN上。

https://blog.csdn.net/m0_72077882/article/details/135653733

文件上传到这了。第一次用github，用的不是很懂。https://github.com/tshiao4695/RIME_XNHEPBID

![动画](https://github.com/mirtlecn/rime-radical-pinyin/assets/50295057/fa485279-8477-4370-a71e-9aa15fb2c644)
