### ISSUE TITLE
使用 reverse_lookup_filter 作为反查滤镜挂载无效

### ISSUE THREAD

**Issue by ChaunceySheng** [mirtlecn/rime-radical-pinyin#13]
不知有没有遇到相同的问题，使用 reverse_lookup_filter 作为反查滤镜挂在双拼方案里，无论如何都无法起效。折腾两小时了，那几句代码核对了不下十遍。还是无法起效。

**Comment by mirtlecn** [comment]
看下雾凇 rime-ice 的写法。

有可能是某个顺序问题。

真搞不明白就发下方案我看下

**Comment by mirtlecn** [comment]
在你的主页看到了你的方案

- 多个 reverse_lookup_translator 要像它这样写： https://github.com/Mintimate/oh-my-rime/blob/52489419e1537e5bde5206b9facb8d970bc76ef1/double_pinyin.schema.yaml#L67-L68

- 用 reverse_lookup_filter 参考我这里，一些 engine 的排序是不能变的。

https://github.com/mirtlecn/rime/blob/master/cn.schema.yaml

- search.lua db 反查数据库你写上了，但没有对应的数据文件会报错。

部分细节有些稍许复杂，需要多研究尝试
