### ISSUE TITLE
二叠字、三叠字、四叠字

### ISSUE THREAD

**Issue by iDvel** [mirtlecn/rime-radical-pinyin#2]
叠字在拼字里还是蛮常用的，且有娱乐目的和用途。
你好像已经加上二、三叠字了，你没在写的话我帮你补上四叠字。

**Comment by mirtlecn** [comment]
可以

https://zh.wikipedia.org/zh-hans/%E5%9B%9B%E5%8F%A0%E5%AD%97

稍等
