### ISSUE TITLE
以前我用两分能打出“𡦀”，现在拆字怎么拆不出了呢？大佬有没有办法加进去呢？

### ISSUE THREAD

**Issue by jslcslx** [mirtlecn/rime-radical-pinyin#2]

**Comment by mirtlecn** [comment]
加了，

用这个 repo 里面的字典文件替换本地字典

或者等雾凇更新

**Comment by jslcslx** [comment]
谢谢

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年04月10日 15:13 |
| 收件人 | mirtlecn/rime-radical-pinyin ***@***.***> |
| 抄送人 | jslcslx ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [mirtlecn/rime-radical-pinyin] 以前我用两分能打出“𡦀”，现在拆字怎么拆不出了呢？大佬有没有办法加进去呢？ (Issue #2) |

Closed #2 as completed.
