### ISSUE TITLE
关于原始字典

### ISSUE THREAD

**Issue by gaboolic** [mirtlecn/rime-radical-pinyin#4]
这个拆字字典非常好用。
想了解下 汉字拆字字典 是怎么生成的。

码表：[汉字拆字字典](https://github.com/mirtlecn/chaizi-re)
字典由 [汉字拆字字典](https://github.com/mirtlecn/chaizi-re)（@開放詞典 / henrysting / Mirtle CC BY-SA 4.0），转换而成。

这个链接没了
能否获得每个字拆分后的部件

**Comment by gaboolic** [comment]
拆字后的部件，和这个项目是否一致？
https://github.com/henrysting/chaizi

**Comment by gaboolic** [comment]
好像也不完全一样
chaizi项目，泰字拆为：	手 乀 水     或者	龹 水
你的项目拆为 手 乀 水     或者	春 水
春 水 更合理些

**Comment by mirtlecn** [comment]
公开了。再去看~

生成脚本在本 repo 的 build 分支。

几个月来手动慢慢改的，原先的词典错有点多。

**Comment by gaboolic** [comment]
这个很不错！
