### ISSUE TITLE
请问如何更改辅码引导键？

### ISSUE THREAD

**Issue by Nickilism** [mirtlecn/rime-radical-pinyin#7]
我用的是仓输入法的双拼方案，在schema文件里默认引导键配置是
```
key_binder:
  import_preset: default  # 从 default.yaml 继承通用的
  search: "`"             # 辅码引导符，要添加到 speller/alphabet
```
此时用"`"能正常进行反查。但是当我将其改成"'"（单引号）时，就不能使用反查了。我也在speller/alphabet加上了单引号。
请教，还有哪里没有设置对吗？

**Comment by mirtlecn** [comment]
发下 build 目录下，你用的双拼方案 schema.yaml，speller 节点下的内容看看

@Nickilism

**Comment by mirtlecn** [comment]
我猜可能是，

单引号是默认的分隔符号，这两冲突了

https://github.com/mirtlecn/rime/blob/master/cn.schema.yaml#L397-L397

你把方案里面的这行注释掉，或者改成其他的试试比如 

```txt
" ^"
```

**Comment by Nickilism** [comment]
> 我猜可能是，
> 
> 单引号是默认的分隔符号，这两冲突了
> 
> https://github.com/mirtlecn/rime/blob/master/cn.schema.yaml#L397-L397
> 
> 你把方案里面的这行注释掉，或者改成其他的试试比如
> 
> ```
> " ^"
> ```

的确是这个原因，现在可以了，谢谢🙏
